version: "3"
services:
  dev:
    image:
    container_name: dev-hot
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: npm run dev
volumes:
  node_modules:
