name: CampingApp CI
on: [push, pull_request]
jobs:
  react-app-workflow:
<<<<<<< HEAD
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
=======
    runs-on: ubuntu-latest
>>>>>>> bac817892466d5ec863dda2e6d9b6837da85f366
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test --if-present
      - name: Check formatting
        run: npm run prettier
      - name: Check linting
        run: npm run lint
      - name: Check types
        run: npm run typescript --if-present
      - name: build
        run: npm run build --if-present
