name: CampingApp CI
on: [push, pull_request]
jobs:
  react-app-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install modules
        run: npm ci
      - name: Run tests
        run: npm run test --if-present
      - name: Check formatting
        run: npm run prettier
      - name: Check linting
        run: npm run lint
      - name: Check types
        run: npm run typescript --if-present
      - name: build
        run: npm run build --if-present
